-- ----------------------------
-- Table structure for `housing`
-- ----------------------------
DROP TABLE IF EXISTS `housing`;
CREATE TABLE `housing` (
  `intId` int(11) NOT NULL AUTO_INCREMENT,
  `charId` char(36) NOT NULL,
  `number` int(6) NOT NULL COMMENT '房源编号',
  `sell_rent` int(1) NOT NULL COMMENT '租售（1 租 2 售 3 租售）',
  `state1` int(1) NOT NULL COMMENT '房源状态（1 有效 2 暂缓 3无效）',
  `state2` int(1) NOT NULL COMMENT '公私盘（1 公 2 私）',
  `level` char(1) NOT NULL COMMENT '等级（A B C D）',
  `customer_charId` char(36) NOT NULL,
  `district_charId` char(36) NOT NULL,
  `area_charId` char(36) NOT NULL,
  `community_charId` char(36) NOT NULL,
  `address1` varchar(50) NOT NULL COMMENT '楼盘名称',
  `address2` varchar(50) NOT NULL COMMENT '物业地址',
  `address3` varchar(50) NOT NULL COMMENT '座幢单元',
  `address4` varchar(50) NOT NULL COMMENT '门牌号',
  `square1` decimal(5,2) NOT NULL COMMENT '建筑面积',
  `square2` decimal(5,2) NOT NULL COMMENT '使用面积',
  `sellPrice1` decimal(5,2) NOT NULL COMMENT '售标价（万）',
  `rentPrice2` decimal(5,2) NOT NULL COMMENT '租标价',
  `sellPrice3` decimal(5,2) NOT NULL COMMENT '售底价（万）',
  `rentPrice4` decimal(5,2) NOT NULL COMMENT '租底价',
  `rentPriceUnit` varchar(50) NOT NULL COMMENT '租价单位（参数）',
  `room1` int(1) NOT NULL COMMENT '室',
  `room2` int(1) NOT NULL COMMENT '厅',
  `room3` int(1) NOT NULL COMMENT '卫',
  `room4` int(1) NOT NULL COMMENT '厨',
  `room5` int(1) NOT NULL COMMENT '阳',
  `floor1` int(1) NOT NULL COMMENT '所在层',
  `floor2` int(1) NOT NULL COMMENT '总楼层',
  `orientation` varchar(50) NOT NULL COMMENT '朝向（参数）',
  `fitment` varchar(50) NOT NULL COMMENT '装修（参数）',
  `type` varchar(50) NOT NULL COMMENT '房源类型（参数）',
  `property1` varchar(50) NOT NULL COMMENT '产权性质（参数）',
  `property2` int(1) NOT NULL COMMENT '产权年限（70 50 40）',
  `property3` date NOT NULL COMMENT '产权日期',
  `structure` varchar(50) NOT NULL COMMENT '建筑结构（参数）',
  `state3` varchar(50) NOT NULL COMMENT '房源现状（参数）',
  `source` varchar(50) NOT NULL COMMENT '房源来源（参数）',
  `takeDate` date NOT NULL COMMENT '来源日期',
  `isDelete` tinyint(1) NOT NULL COMMENT '是否删除（1 是 2 否）',
  `description` varchar(255) NOT NULL COMMENT '备注描述',
  `createTime` datetime NOT NULL COMMENT '创建日期',
  `createInfo` varchar(50) NOT NULL COMMENT '创建者',
  `create_department_rowId` char(36) NOT NULL,
  `create_employee_rowId` char(36) NOT NULL,
  `ownerInfo` varchar(50) NOT NULL COMMENT '所属者',
  `owner_department_rowId` char(36) NOT NULL,
  `owner_employee_rowId` char(36) NOT NULL,
  PRIMARY KEY (`intId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;